<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use Illuminate\Support\Facades\Storage;
use Illuminate\Support\Str;

class PayrollController extends Controller
{
    // Show the upload form and (optionally) processed results
    public function index(Request $request)
    {
        $processed = session('payroll_processed');
        return view('payroll.upload', compact('processed'));
    }

    // Handle upload and processing
    public function upload(Request $request)
    {
        $request->validate([
            'payroll_file' => 'required|file',
        ]);

        $file = $request->file('payroll_file');
        $ext = strtolower($file->getClientOriginalExtension());
        $rows = [];

        // If PhpSpreadsheet available and file is xls/xlsx
        if (in_array($ext, ['xls','xlsx']) && class_exists('\PhpOffice\PhpSpreadsheet\IOFactory')) {
            try {
                $spreadsheet = \PhpOffice\PhpSpreadsheet\IOFactory::load($file->getRealPath());
                $sheet = $spreadsheet->getActiveSheet();
                foreach ($sheet->getRowIterator() as $row) {
                    $cellIterator = $row->getCellIterator();
                    $cellIterator->setIterateOnlyExistingCells(false);
                    $rowData = [];
                    foreach ($cellIterator as $cell) {
                        $rowData[] = $cell->getValue();
                    }
                    $rows[] = $rowData;
                }
            } catch (\Exception $e) {
                return back()->withErrors(['payroll_file' => 'Failed to read spreadsheet: '.$e->getMessage()]);
            }
        } else {
            // Try CSV parsing
            if (!in_array($ext, ['csv','txt'])) {
                return back()->withErrors(['payroll_file' => 'Unsupported file type. Upload CSV or XLS/XLSX']);
            }
            if (($handle = fopen($file->getRealPath(), 'r')) !== false) {
                while (($data = fgetcsv($handle)) !== false) {
                    $rows[] = $data;
                }
                fclose($handle);
            } else {
                return back()->withErrors(['payroll_file' => 'Failed to open uploaded file']);
            }
        }

        if (count($rows) < 1) {
            return back()->withErrors(['payroll_file' => 'No data found in file']);
        }

        // Remove footer or metadata rows that some attendance exports include
        $rows = array_values(array_filter($rows, function($r) {
            $text = strtolower(implode(' ', array_map(function($c){ return is_null($c) ? '' : (string)$c; }, $r)));
            $tokens = ['generated by', 'ontime', 'secureye'];
            foreach ($tokens as $t) {
                if (strpos($text, $t) !== false) return false;
            }
            return true;
        }));

        // Detect header row
        $headerRowIndex = 0;
        $maxHeaderSearch = min(10, count($rows)-1);
        $found = false;
        for ($i = 0; $i <= $maxHeaderSearch; $i++) {
            $r = $rows[$i];
            foreach ($r as $cell) {
                $c = is_null($cell) ? '' : trim((string)$cell);
                $lc = Str::lower($c);
                if (Str::contains($lc, 'emp') && Str::contains($lc, 'code')) {
                    $headerRowIndex = $i;
                    $found = true;
                    break 2;
                }
                if ($lc === 'emp code' || $lc === 'emp_code' || $lc === 'empid') {
                    $headerRowIndex = $i;
                    $found = true;
                    break 2;
                }
            }
        }
        $header = array_map(function($h){ return is_null($h) ? '' : trim((string)$h); }, $rows[$headerRowIndex]);

        // Find indexes
        $empCodeIdx = null; $empNameIdx = null; $dayIndexes = [];
        foreach ($header as $i => $h) {
            $lh = Str::lower($h);
            if ($empCodeIdx === null && ($lh === 'emp code' || $lh === 'emp_code' || $lh === 'empid' || $lh === 'emp id' || $lh === 'code')) {
                $empCodeIdx = $i;
            }
            if ($empNameIdx === null && (Str::contains($lh, 'emp') && Str::contains($lh, 'name') || $lh === 'name')) {
                $empNameIdx = $i;
            }
            // day columns numeric
            if (is_numeric($h) && intval($h) >=1 && intval($h) <= 31) {
                $dayIndexes[intval($h)] = $i;
            }
        }

        // Fallback: assume first col = code, second = name, rest days
        if ($empCodeIdx === null) $empCodeIdx = 0;
        if ($empNameIdx === null) $empNameIdx = 1;
        if (empty($dayIndexes)) {
            for ($d=1;$d<=31;$d++) {
                $idx = 2 + ($d-1);
                if (isset($header[$idx])) $dayIndexes[$d] = $idx;
            }
        }

        $processed = [];

        // NEW TIMINGS as per requirements
        $standardIn = strtotime('09:20');      // Check-in at 9:20
        $lateThreshold = strtotime('09:21');   // After 9:21 is late
        $standardOut = strtotime('16:55');     // Check-out at 4:55 PM (16:55)

        // Data starts after header row
        $dataStart = $headerRowIndex + 1;
        for ($r=$dataStart;$r<count($rows);$r++) {
            $row = $rows[$r];
            // skip if empty
            if (!isset($row[$empCodeIdx]) && !isset($row[$empNameIdx])) continue;
            $code = trim($row[$empCodeIdx] ?? '');
            $name = trim($row[$empNameIdx] ?? '');
            if ($code === '' && $name === '') continue;
            
            $entry = [
                'code'=>$code,
                'name'=>$name,
                'days'=>[],
                'late_count'=>0,
                'early_count'=>0,
                'absent_count'=>0,
                'extra_count'=>0,
                'extra_times'=>[], 
                'half_day_count'=>0,
                'total_leave_days'=>0
            ];
            
            foreach ($dayIndexes as $day => $idx) {
                $cell = isset($row[$idx]) ? trim($row[$idx]) : '';
                
                // If cell is empty, mark as 'M' (Missing/Absent)
                if ($cell === '') {
                    $entry['days'][$day] = [
                        'in'=>null,
                        'out'=>null,
                        'late_minutes'=>0,
                        'status'=>'M',
                        'is_absent'=>true
                    ];
                    $entry['absent_count']++;
                    continue;
                }
                
                // Normalize cell and detect absent codes
                $cellNorm = trim((string)$cell);
                $cellUpper = Str::upper($cellNorm);
                
                // Check for WO (Weekly Off) - should remain as WO, remove 'A'
                if ($cellUpper === 'WO' || $cellUpper === 'WO-1' || $cellUpper === 'WO-I' || $cellUpper === 'WO I' || $cellUpper === 'WOI') {
                    $entry['days'][$day] = [
                        'in'=>null,
                        'out'=>null,
                        'late_minutes'=>0,
                        'status'=>'WO',
                        'is_absent'=>false
                    ];
                    continue;
                }
                
                // Check for Absent 'A' or 'ABSENT'
                if ($cellUpper === 'A' || $cellUpper === 'ABSENT') {
                    $entry['days'][$day] = [
                        'in'=>null,
                        'out'=>null,
                        'late_minutes'=>0,
                        'status'=>'A',
                        'is_absent'=>true
                    ];
                    $entry['absent_count']++;
                    continue;
                }

                $in = null; $out = null; $late = 0;
                
                // Extract all time-like patterns
                $timesFound = [];
                if (preg_match_all('/(\d{1,2}:\d{2})/', $cellNorm, $m1)) {
                    foreach ($m1[1] as $t) $timesFound[] = $t;
                }
                if (preg_match_all('/\b(\d{3,4})\b/', $cellNorm, $m2)) {
                    foreach ($m2[1] as $tn) {
                        $t = $tn;
                        if (strlen($t) === 3) $t = substr($t,0,1).':'.substr($t,1);
                        if (strlen($t) === 4) $t = substr($t,0,2).':'.substr($t,2);
                        $timesFound[] = $t;
                    }
                }

                // Deduplicate and normalize times
                $timesNorm = [];
                foreach ($timesFound as $t) {
                    $t = trim($t);
                    if (preg_match('/^\d{1,2}:\d{2}$/', $t)) {
                        $timesNorm[] = $t;
                    }
                }
                
                if (!empty($timesNorm)) {
                    // convert to timestamps and pick earliest as IN and latest as OUT
                    $ts = array_map(function($x){ return strtotime($x); }, $timesNorm);
                    sort($ts);
                    $in = date('H:i', $ts[0]);
                    if (count($ts) > 1) $out = date('H:i', $ts[count($ts)-1]);

                    $tin = strtotime($in);
                    if ($tin > $standardIn) {
                        $late = intval(($tin - $standardIn)/60);
                    }
                }
                
                // Check if only one punch exists (missing check-in or check-out)
                if (($in && !$out) || (!$in && $out)) {
                    // Missing either check-in or check-out = treat as absent
                    $entry['days'][$day] = [
                        'in'=>$in,
                        'out'=>$out,
                        'late_minutes'=>0,
                        'status'=>'A',
                        'is_absent'=>true
                    ];
                    $entry['absent_count']++;
                    continue; // Skip further processing for this day
                }
                
                // Determine late checkin (after 09:20) and early checkout (before 16:55)
                $isLate = false; $isEarly = false;
                if ($in) {
                    $tin = strtotime($in);
                    if ($tin > $lateThreshold) {  // After 9:21
                        $isLate = true;
                    }
                }
                if ($out) {
                    $tout = strtotime($out);
                    if ($tout < $standardOut) {  // Before 4:55 PM
                        $isEarly = true;
                    } elseif ($tout > strtotime('17:30')) {
                        // checkout after 5:30 PM (17:30) - count as extra time
                        $entry['extra_count']++;
                        $entry['extra_times'][] = $day . ':' . date('H:i', $tout);
                    }
                }

                // Check for half-day conditions
                $isHalfDay = false;
                if ($in && $out) {
                    $tin = strtotime($in);
                    $tout = strtotime($out);
                    $halfDayInThreshold = strtotime('10:00');  // Check-in after 10:00 AM
                    $halfDayOutThreshold = strtotime('13:45'); // Check-out after 1:45 PM
                    
                    // Half-day if check-in is after 10:00 OR checkout is before 1:45
                    if ($tin > $halfDayInThreshold || $tout < $halfDayOutThreshold) {
                        $isHalfDay = true;
                        $entry['half_day_count']++;
                    }
                }

                if ($isLate) $entry['late_count']++;
                if ($isEarly) $entry['early_count']++;

                $entry['days'][$day] = [
                    'in'=>$in,
                    'out'=>$out,
                    'late_minutes'=>$late,
                    'is_late'=>$isLate,
                    'is_early'=>$isEarly,
                    'is_half_day'=>$isHalfDay,
                    'status'=>'P'
                ];
            }
            // NEW LEAVE CALCULATION LOGIC
            // Combined late check-ins + early checkouts:
            // - 3-5 total = 0.5 day leave
            // - 6-11 total = 1 day leave
            // - 12-14 total = 2 days leave
            // - 15-17 total = 2.5 days leave
            // - 18-20 total = 3 days leave
            // - 21-23 total = 3.5 days leave
            // - 24-26 total = 4 days leave
            // - 27+ total = proportional increase (4 + additional 0.5 for every 3 violations)
            $total_violations = $entry['late_count'] + $entry['early_count'];
            $leave = 0;
            if ($total_violations >= 27) {
                // For 27+, calculate: 4 days + 0.5 for every additional 3 violations
                $extra_violations = $total_violations - 24;
                $leave = 4 + (floor($extra_violations / 3) * 0.5);
            } elseif ($total_violations >= 24) {
                $leave = 4;
            } elseif ($total_violations >= 21) {
                $leave = 3.5;
            } elseif ($total_violations >= 18) {
                $leave = 3;
            } elseif ($total_violations >= 15) {
                $leave = 2.5;
            } elseif ($total_violations >= 12) {
                $leave = 2;
            } elseif ($total_violations >= 6) {
                $leave = 1;
            } elseif ($total_violations >= 3) {
                $leave = 0.5;
            } else {
                $leave = 0;
            }
            
            // Add absent days and half days to total leave
            // Total = violation-based leave + absent days + (half days * 0.5)
            $leave_from_half_days = $entry['half_day_count'] * 0.5;
            $entry['total_leave_days'] = $leave + $entry['absent_count'] + $leave_from_half_days;
            $processed[] = $entry;
        }

        // Save to session for display
        session(['payroll_processed' => $processed]);
        return redirect()->route('payroll.index');

    }

    // Export payroll data to CSV

    public function export(Request $request)
    {
        $processed = session('payroll_processed');
        
        if (!$processed) {
            return back()->withErrors(['payroll_file' => 'No data to export. Please upload a file first.']);
        }
        
        $filename = 'payroll_export_' . date('Y-m-d_His') . '.csv';
        
        $headers = [
            'Content-Type' => 'text/csv',
            'Content-Disposition' => 'attachment; filename="' . $filename . '"',
        ];
        
        $callback = function() use ($processed) {
            $file = fopen('php://output', 'w');
            
            // Add CSV header row
            fputcsv($file, ['Emp Name', 'Late Checkins', 'Early Checkouts', 'Extra Days (post 5:30 PM)', 'Absent Days', 'Half Days', 'Total Leave (days)']);
            
            // Add data rows
            foreach ($processed as $p) {
                fputcsv($file, [
                    $p['name'],
                    $p['late_count'],
                    $p['early_count'],
                    $p['extra_count'] ?? 0,
                    $p['absent_count'] ?? 0,
                    $p['half_day_count'] ?? 0,
                    $p['total_leave_days']
                ]);
            }
            
            fclose($file);
        };
        
        return response()->stream($callback, 200, $headers);
    }
}
