<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use Illuminate\Support\Facades\Storage;
use Illuminate\Support\Str;

class PayrollController extends Controller
{
    // Show the upload form and (optionally) processed results
    public function index(Request $request)
    {
        $processed = session('payroll_processed');
        session()->forget('payroll_processed');
        return view('payroll.upload', compact('processed'));
    }

    // Handle upload and processing
    public function upload(Request $request)
    {
        $request->validate([
            'payroll_file' => 'required|file',
        ]);

        $file = $request->file('payroll_file');
        $ext = strtolower($file->getClientOriginalExtension());
        $rows = [];

        // If PhpSpreadsheet available and file is xls/xlsx
        if (in_array($ext, ['xls','xlsx']) && class_exists('\PhpOffice\PhpSpreadsheet\IOFactory')) {
            try {
                $spreadsheet = \PhpOffice\PhpSpreadsheet\IOFactory::load($file->getRealPath());
                $sheet = $spreadsheet->getActiveSheet();
                foreach ($sheet->getRowIterator() as $row) {
                    $cellIterator = $row->getCellIterator();
                    $cellIterator->setIterateOnlyExistingCells(false);
                    $rowData = [];
                    foreach ($cellIterator as $cell) {
                        $rowData[] = $cell->getValue();
                    }
                    $rows[] = $rowData;
                }
            } catch (\Exception $e) {
                return back()->withErrors(['payroll_file' => 'Failed to read spreadsheet: '.$e->getMessage()]);
            }
        } else {
            // Try CSV parsing
            if (!in_array($ext, ['csv','txt'])) {
                return back()->withErrors(['payroll_file' => 'Unsupported file type. Upload CSV or XLS/XLSX']);
            }
            if (($handle = fopen($file->getRealPath(), 'r')) !== false) {
                while (($data = fgetcsv($handle)) !== false) {
                    $rows[] = $data;
                }
                fclose($handle);
            } else {
                return back()->withErrors(['payroll_file' => 'Failed to open uploaded file']);
            }
        }

        if (count($rows) < 1) {
            return back()->withErrors(['payroll_file' => 'No data found in file']);
        }

        // Remove footer or metadata rows that some attendance exports include
        // e.g., "Generated By : ONtime (Secureye)" - skip rows containing these tokens
        $rows = array_values(array_filter($rows, function($r) {
            $text = strtolower(implode(' ', array_map(function($c){ return is_null($c) ? '' : (string)$c; }, $r)));
            $tokens = ['generated by', 'ontime', 'secureye'];
            foreach ($tokens as $t) {
                if (strpos($text, $t) !== false) return false;
            }
            return true;
        }));

        // Detect header row (sheet may contain title rows before header)
        $headerRowIndex = 0;
        $maxHeaderSearch = min(10, count($rows)-1);
        $found = false;
        for ($i = 0; $i <= $maxHeaderSearch; $i++) {
            $r = $rows[$i];
            foreach ($r as $cell) {
                $c = is_null($cell) ? '' : trim((string)$cell);
                $lc = Str::lower($c);
                if (Str::contains($lc, 'emp') && Str::contains($lc, 'code')) {
                    $headerRowIndex = $i;
                    $found = true;
                    break 2;
                }
                if ($lc === 'emp code' || $lc === 'emp_code' || $lc === 'empid') {
                    $headerRowIndex = $i;
                    $found = true;
                    break 2;
                }
            }
        }
        $header = array_map(function($h){ return is_null($h) ? '' : trim((string)$h); }, $rows[$headerRowIndex]);

        // Expected header contains something like: Emp code, Emp name, 1,2,3,...31
        // Find indexes
        $empCodeIdx = null; $empNameIdx = null; $dayIndexes = [];
        foreach ($header as $i => $h) {
            $lh = Str::lower($h);
            if ($empCodeIdx === null && ($lh === 'emp code' || $lh === 'emp_code' || $lh === 'empid' || $lh === 'emp id' || $lh === 'code')) {
                $empCodeIdx = $i;
            }
            if ($empNameIdx === null && (Str::contains($lh, 'emp') && Str::contains($lh, 'name') || $lh === 'name')) {
                $empNameIdx = $i;
            }
            // day columns numeric
            if (is_numeric($h) && intval($h) >=1 && intval($h) <= 31) {
                $dayIndexes[intval($h)] = $i;
            }
        }

        // Fallback: assume first col = code, second = name, rest days
        if ($empCodeIdx === null) $empCodeIdx = 0;
        if ($empNameIdx === null) $empNameIdx = 1;
        if (empty($dayIndexes)) {
            // map next 31 columns
            for ($d=1;$d<=31;$d++) {
                $idx = 2 + ($d-1);
                if (isset($header[$idx])) $dayIndexes[$d] = $idx;
            }
        }

        $processed = [];

        // Standard timings
        $standardIn = strtotime('09:30');
            $lateThreshold = strtotime('09:35');
            $standardOut = strtotime('17:30');

        // Data starts after header row
        $dataStart = $headerRowIndex + 1;
        for ($r=$dataStart;$r<count($rows);$r++) {
            $row = $rows[$r];
            // skip if empty
            if (!isset($row[$empCodeIdx]) && !isset($row[$empNameIdx])) continue;
            $code = trim($row[$empCodeIdx] ?? '');
            $name = trim($row[$empNameIdx] ?? '');
            if ($code === '' && $name === '') continue;
            $entry = ['code'=>$code,'name'=>$name,'days'=>[],'late_count'=>0,'early_count'=>0,'extra_count'=>0,'extra_times'=>[], 'total_leave_days'=>0];
            foreach ($dayIndexes as $day => $idx) {
                $cell = isset($row[$idx]) ? trim($row[$idx]) : '';
                if ($cell === '') {
                    $entry['days'][$day] = ['in'=>null,'out'=>null,'late_minutes'=>0];
                    continue;
                }
                // Normalize cell and detect absent codes
                $cellNorm = trim((string)$cell);
                $cellUpper = Str::upper($cellNorm);
                $absentTokens = ['A','ABSENT','WO','WO-1','WO-I','WO I','WOI','OFF'];
                $isAbsent = false;
                foreach ($absentTokens as $tok) {
                    if ($cellUpper === $tok || Str::contains($cellUpper, $tok)) {
                        $isAbsent = true;
                        break;
                    }
                }

                $in = null; $out = null; $late = 0;
                if (!$isAbsent && $cellNorm !== '') {
                    // Extract all time-like patterns (HH:MM) and numeric times (930,1745)
                    $timesFound = [];
                    if (preg_match_all('/(\d{1,2}:\d{2})/', $cellNorm, $m1)) {
                        foreach ($m1[1] as $t) $timesFound[] = $t;
                    }
                    if (preg_match_all('/\b(\d{3,4})\b/', $cellNorm, $m2)) {
                        foreach ($m2[1] as $tn) {
                            $t = $tn;
                            if (strlen($t) === 3) $t = substr($t,0,1).':'.substr($t,1);
                            if (strlen($t) === 4) $t = substr($t,0,2).':'.substr($t,2);
                            $timesFound[] = $t;
                        }
                    }

                    // Deduplicate and normalize times
                    $timesNorm = [];
                    foreach ($timesFound as $t) {
                        $t = trim($t);
                        if (preg_match('/^\d{1,2}:\d{2}$/', $t)) {
                            $timesNorm[] = $t;
                        }
                    }
                    if (!empty($timesNorm)) {
                        // convert to timestamps and pick earliest as IN and latest as OUT
                        $ts = array_map(function($x){ return strtotime($x); }, $timesNorm);
                        sort($ts);
                        $in = date('H:i', $ts[0]);
                        if (count($ts) > 1) $out = date('H:i', $ts[count($ts)-1]);

                        $tin = strtotime($in);
                        if ($tin > $standardIn) {
                            $late = intval(($tin - $standardIn)/60);
                        }
                    }
                }
                // determine late checkin (after 09:35) and early checkout (before 17:30)
                $isLate = false; $isEarly = false;
                if ($in) {
                    $tin = strtotime($in);
                    if ($tin > $lateThreshold) {
                        $isLate = true;
                    }
                }
                if ($out) {
                    $tout = strtotime($out);
                    if ($tout < $standardOut) {
                        $isEarly = true;
                    } elseif ($tout > $standardOut) {
                        // checkout after standard out - count as extra time
                        $entry['extra_count']++;
                        $entry['extra_times'][] = $day . ':' . date('H:i', $tout);
                    }
                }

                if ($isLate) $entry['late_count']++;
                if ($isEarly) $entry['early_count']++;

                $entry['days'][$day] = ['in'=>$in,'out'=>$out,'late_minutes'=>$late,'is_late'=>$isLate,'is_early'=>$isEarly];
            }
            // compute total leave from late_count using rules:
            // <=2 -> 0 days
            // 3-5 -> 0.5 day
            // 6-12 -> 1 day
            // >12 -> 2 days
            $lc = $entry['late_count'];
            $leave = 0;
            if ($lc <= 2) {
                $leave = 0;
            } elseif ($lc >=3 && $lc <=5) {
                $leave = 0.5;
            } elseif ($lc >=6 && $lc <=12) {
                $leave = 1;
            } elseif ($lc > 12) {
                $leave = 2;
            }
            $entry['total_leave_days'] = $leave;

            $processed[] = $entry;
        }

        // Save to session for display
        session(['payroll_processed' => $processed]);

        return redirect()->route('payroll.index');
    }
}
